# Generated by Django 5.2.10 on 2026-01-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stacks_address',
            field=models.CharField(blank=True, db_index=True, help_text='Stacks wallet address', max_length=255, null=True, unique=True),
        ),
    ]
