# Generated by Django 5.2.10 on 2026-01-30 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0002_initial'),
        ('news', '0002_initial'),
        ('shows', '0002_initial'),
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news'),
        ),
        migrations.AddField(
            model_name='comment',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_direct', to='shows.show'),
        ),
        migrations.AddField(
            model_name='like',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='events.event'),
        ),
        migrations.AddField(
            model_name='like',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.news'),
        ),
        migrations.AddField(
            model_name='like',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_direct', to='shows.show'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['show'], name='users_comme_show_id_f004c3_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['show'], name='users_like_show_id_d9eaa9_idx'),
        ),
    ]
