# Generated by Django 5.2.10 on 2026-01-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_alter_like_unique_together_comment_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='users_comme_show_id_f004c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='users_like_show_id_d9eaa9_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='show',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='like',
            name='event',
        ),
        migrations.RemoveField(
            model_name='like',
            name='news',
        ),
        migrations.RemoveField(
            model_name='like',
            name='show',
        ),
    ]
