# Generated by Django 5.2.10 on 2026-02-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
    ]
