# Generated by Django 5.2.10 on 2026-02-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_follow_options_alter_like_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('show_reminder', 'Show Reminder'), ('show_cancelled', 'Show Cancelled')], max_length=20),
        ),
    ]
