# Generated by Django 5.2.10 on 2026-02-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_start_d_8d5b46_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_organiz_313015_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='comment_count',
            field=models.IntegerField(default=0, help_text='Number of comments (cached)'),
        ),
        migrations.AddField(
            model_name='event',
            name='like_count',
            field=models.IntegerField(default=0, help_text='Number of likes (cached)'),
        ),
        migrations.AddField(
            model_name='event',
            name='share_count',
            field=models.IntegerField(default=0, help_text='Number of shares'),
        ),
    ]
