# Generated by Django 5.2.10 on 2026-02-09 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='share_count',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime', 'is_public'], name='events_even_start_d_8d5b46_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', '-start_datetime'], name='events_even_organiz_313015_idx'),
        ),
    ]
