# Generated by Django 5.2.10 on 2026-01-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for previews', max_length=500)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/featured/')),
                ('category', models.CharField(choices=[('general', 'General'), ('announcement', 'Announcement'), ('update', 'Update'), ('feature', 'Feature'), ('review', 'Review'), ('interview', 'Interview')], default='general', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
