# Generated by Django 5.2.10 on 2026-01-18 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_published', '-published_at'], name='news_news_is_publ_dcad2b_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['author', '-published_at'], name='news_news_author__abc2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', '-published_at'], name='news_news_categor_83f27b_idx'),
        ),
    ]
