# Generated by Django 5.2.10 on 2026-01-18 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='creator',
            field=models.ForeignKey(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showepisode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.show'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['status', '-created_at'], name='shows_show_status_d13842_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['creator', 'status'], name='shows_show_creator_10d79d_idx'),
        ),
        migrations.AddIndex(
            model_name='showepisode',
            index=models.Index(fields=['show', 'air_date'], name='shows_showe_show_id_aa71b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='showepisode',
            unique_together={('show', 'episode_number')},
        ),
    ]
