# Generated by Django 5.2.10 on 2026-02-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='show',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to external content (YouTube, Twitter Space, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='link_platform',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('twitch', 'Twitch'), ('rumble', 'Rumble'), ('kick', 'Kick'), ('other', 'Other')], help_text='Platform for the external link', max_length=20),
        ),
        migrations.AddField(
            model_name='show',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='shows', to='shows.tag'),
        ),
    ]
