# Generated by Django 5.2.10 on 2026-02-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_tag_show_external_link_show_link_platform_show_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cancelled_instances',
            field=models.JSONField(blank=True, default=list, help_text='List of ISO date strings for cancelled recurring show instances'),
        ),
        migrations.AddField(
            model_name='show',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('SPECIFIC_DAY', 'Specific Day'), ('DAILY', 'Daily'), ('WEEKDAYS', 'Weekdays (Mon-Fri)'), ('WEEKENDS', 'Weekends (Sat-Sun)')], help_text='Type of recurrence pattern', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week for SPECIFIC_DAY recurring shows (0=Monday, 6=Sunday)', null=True),
        ),
        migrations.CreateModel(
            name='ShowReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(help_text='Specific datetime this show instance is scheduled for')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('creator_response', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='shows.show')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['show', 'scheduled_for'], name='shows_showr_show_id_5330d3_idx'), models.Index(fields=['creator_response', 'scheduled_for'], name='shows_showr_creator_205bd9_idx')],
                'unique_together': {('show', 'scheduled_for')},
            },
        ),
    ]
