# Generated by Django 5.2.10 on 2026-02-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_show_cancelled_instances_show_recurrence_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
