# Generated by Django 5.2.10 on 2026-02-05 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_sharerecord_remove_show_shows_show_status_d13842_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerecord',
            name='show',
        ),
        migrations.RemoveIndex(
            model_name='show',
            name='shows_show_status_957016_idx',
        ),
        migrations.RemoveField(
            model_name='show',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='show',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='show',
            name='share_count',
        ),
        migrations.RemoveField(
            model_name='show',
            name='view_count',
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['status', '-created_at'], name='shows_show_status_d13842_idx'),
        ),
        migrations.DeleteModel(
            name='ShareRecord',
        ),
    ]
