# Generated by Django 5.2.10 on 2026-02-05 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_remove_sharerecord_show_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='share_count',
            field=models.IntegerField(default=0, help_text='Number of times this show has been shared'),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['slug'], name='shows_show_slug_83daa9_idx'),
        ),
    ]
